// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace MeWeTest{
    [TestFixture]
    public class UnitTest1 : TestBase
    {
        
        [Test]
        public void login()
        {
            AccountData user = new AccountData("fatikoff2002@mail.ru", "DaniilFatykov");
            OpenLoginPage();
            MangeWindow();
            Login(user);
        }

        [Test]
        public void post()
        {
            AccountData user = new AccountData("fatikoff2002@mail.ru", "DaniilFatykov");
            GroupData post = new GroupData("Hello world") { Header = "sds", Footer = "dsfsd" }; ;
            OpenLoginPage();
            MangeWindow();
            Login(user);
            Thread.Sleep(50000);
            OpenProfilePage();
            Thread.Sleep(5000);
            NewPost(post);
        }
    }
}

